---
title: "Installation Instructions for scCustomize"
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: rmarkdown::html_vignette
theme: united
df_print: kable
vignette: >
  %\VignetteIndexEntry{Installation Instructions for scCustomize}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
***

<style>
p.caption {
  font-size: 0.9em;
}
</style>
 
```{r setup, include=FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  time_it = TRUE
)
```

scCustomize requires [R](https://www.r-project.org/) version 4.0 or greater. Highly recommend installing [R Studio](https://www.rstudio.com/).

# Install from GitHub  
scCustomize can be installed from GitHub using either devtools or remotes package:

## Package Requirements
scCustomize has one import dependency requirement that needs to be updated if previously installed (if not installed they will be automatically installed during scCustomize installation).
  
* [colorway](https://github.com/hypercompetent/colorway) >= v0.2.0.

## Install
scCustomize can be installed using either devtools or remotes package
```
devtools::install_github(repo = "samuel-marsh/scCustomize")

remotes::install_github(repo = "samuel-marsh/scCustomize")
```

## Master branch    
Full releases will be available on the master branch with version scheme vX.X.X.  
See [NEWS/ChangeLog](https://samuel-marsh.github.io/scCustomize/news/index.html) file for ChangeLog with additions, changes, and fixes contained in each release.

## Develop branch    
I also maintain a separate development branch<sup>\*</sup> that can be installed by supplying `ref = "develop"` in the devtools or remotes installation command.  Version scheme vX.X.X.yyyy.  

```
devtools::install_github(repo = "samuel-marsh/scCustomize", ref = "develop")

remotes::install_github(repo = "samuel-marsh/scCustomize", ref = "develop")
```

<sup>\*</sup>*Note: While this branch is typically mostly stable it may contain breaking issues/bugs.*  
I do try and keep [development ChangeLog](https://github.com/samuel-marsh/scCustomize/blob/develop/NEWS.md) up to date so it's easier to follow changes than reading commit history.
